language: cpp

os:
  - linux
  - windows
      
script:
    - mkdir -p build
    - cd build
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        cmake ..
      fi
    - |
      if [[ ${TRAVIS_OS_NAME} == "windows" ]]; then
        cmake -DCMAKE_GENERATOR_PLATFORM=x64 ..
      fi
    - cmake --build . --config release