language: cpp

jobs:
  include:
    - os: linux
      arch: arm64
    - os: linux
      arch: amd64
    - os: windows
      arch: amd64
    - os: osx
      arch: amd64

branches:
  only:
    - master
      
script:
    - mkdir build
    - cd build
    - if [[ ${TRAVIS_OS_NAME} == "windows" ]]; then
        cmake -DCMAKE_GENERATOR_PLATFORM=x64 ..;
      else
        cmake ..;
      fi
    - cmake --build . --config release